[system]
# Load language from environment variable(It is set by the hook)
language = "${env:DBGPT_LANG:-en}"
api_keys = []
encrypt_key = "your_secret_key"
log_level = "WARNING"

# Server Configurations
[service.web]
host = "0.0.0.0"
port = 5670

[service.web.database]
type = "mysql"
host = "backup-polardb-history.rwlb.rds.aliyuncs.com"
port = 3306
database = "ekb400"
user = "sql_review"
password = "M3TTsyAhXy8Xn3PZf2vH"

[rag.storage]
[rag.storage.vector]
type = "chroma"
persist_path = "pilot/data"

# Model Configurations
[models]
[[models.llms]]
name = "glm-5.2"
provider = "proxy/openai"
api_base = "https://ai-gateway-prod.hosecloud.com/coding-plan/v1"
api_key = "${env:OPENAI_API_KEY}"

[[models.embeddings]]
name = "Qwen3-Embedding-8B"
provider = "proxy/openai"
api_url = "https://ai-gateway-prod.hosecloud.com/coding-plan-emb/v1/embeddings"
api_key = "${env:OPENAI_API_KEY}"
